from __future__ import annotations

from typing import Any


def score_knowledge_object(obj: dict[str, Any], obj_type: str = "saved_search") -> dict[str, Any]:
    """
    Score a knowledge object 0-100 across 7 dimensions.

    MCP_BLOCKER = the FINAL mcp_description is empty AFTER the pipeline ran.
    health_issues from the scanner are for SPL/config issues only — not for
    the description, which is generated by this tool.
    """
    score = 0
    breakdown: dict[str, int] = {}
    issues = obj.get("health_issues", []) or []
    spl = obj.get("search", "") or obj.get("definition", "") or ""

    # ── 1. Description Quality (0–35) ─────────────────────────────────────────
    # Score the BEST available description:
    #   • mcp_description  → AI-generated by this tool (after pipeline)
    #   • description      → original built-in Splunk description (fallback)
    # This means objects with existing descriptions are never scored 0.
    # Both individual scores are stored for the visual diff in the report.
    mcp_desc  = (obj.get("mcp_description") or "").strip()
    orig_desc = (obj.get("description") or "").strip()
    best_desc = mcp_desc or orig_desc   # prefer AI-generated, fall back to original

    ACTION_VERBS = ["use when", "use this", "returns", "detects", "identifies",
                    "monitors", "alerts", "tracks", "counts", "filters", "surfaces",
                    "queries", "analyzes", "exposes"]

    def _desc_score(text: str) -> int:
        t = text.lower()
        has_action      = any(v in t for v in ACTION_VERBS)
        has_data_source = any(k in t for k in
                              ["index=", "sourcetype=", "datamodel=", "lookup=", "from ",
                               "via ", "rest api", "splunk event", "splunk data"])
        has_trigger     = any(k in t for k in
                              ["when ", "use when", "use this when", "if ", "exceed",
                               "threshold", "anomal", "investigate", "team needs"])
        if len(text) >= 120 and has_action and has_data_source and has_trigger:
            return 35
        if len(text) >= 80 and has_action and (has_data_source or has_trigger):
            return 25
        if len(text) >= 40 and (has_action or has_trigger):
            return 15
        if len(text) >= 20:
            return 8    # present but generic — still not 0
        return 0        # truly empty

    desc_score = _desc_score(best_desc)
    breakdown["description"] = desc_score
    score += desc_score

    # Store both for report diff chips
    obj["orig_desc_score"] = _desc_score(orig_desc)
    obj["ai_desc_score"]   = _desc_score(mcp_desc)

    # Tag whether this object had NO description in Splunk before our tool ran
    orig_desc_present = bool(orig_desc)
    obj["had_original_description"] = orig_desc_present
    # MCP blocker = BOTH original AND AI description are missing.
    # If our AI generated a description, the object is no longer a blocker
    # because the patch will fix it. Only truly un-describable objects block.
    ai_desc_present = bool(mcp_desc)
    obj["is_mcp_blocker"] = not orig_desc_present and not ai_desc_present


    # ── 2. AI Explanation Richness (0–15) ─────────────────────────────────────
    # Rewards objects that got real Gemini-quality plain_english and business_question
    plain = (obj.get("plain_english") or "").strip()
    biz_q = (obj.get("business_question") or "").strip()

    # Penalise heuristic-quality output (contains template phrases)
    HEURISTIC_PHRASES = ["Runs SPL to find events for", "Searches Not explicit in SPL",
                         "Expands macro", "What does '", "reveal about unknown operations"]
    is_heuristic_plain = any(p in plain for p in HEURISTIC_PHRASES)
    is_heuristic_biz   = any(p in biz_q for p in HEURISTIC_PHRASES)

    ai_score = 0
    if len(plain) > 80 and not is_heuristic_plain:
        ai_score += 8    # rich AI-generated explanation
    elif len(plain) > 80:
        ai_score += 3    # heuristic, at least has content
    if len(biz_q) > 30 and not is_heuristic_biz:
        ai_score += 7    # meaningful business question
    elif len(biz_q) > 30:
        ai_score += 2    # heuristic filler question
    breakdown["ai_enrichment"] = ai_score
    score += ai_score

    # ── 3. Data Activity (0–15) ───────────────────────────────────────────────
    activity = obj.get("activity")
    if activity is None:
        breakdown["active"] = 5   # unknown — slight penalty
        score += 5
    elif activity.get("active"):
        breakdown["active"] = 15
        score += 15
    elif activity.get("error"):
        breakdown["active"] = 5
        score += 5
    else:
        breakdown["active"] = 0   # confirmed no data

    # ── 4. SPL Health Issues (0–15) ───────────────────────────────────────────
    # Only count scanner-detected SPL/config issues — NOT missing_mcp_description
    # (that's handled in dimension 1 using the final generated description)
    real_issues = [i for i in issues if i.get("type") != "missing_mcp_description"]
    critical = [i for i in real_issues if i.get("severity") == "ERROR"]
    warnings  = [i for i in real_issues if i.get("severity") == "WARNING"]

    if not critical and not warnings:
        health_score = 15
    elif not critical:
        health_score = 10
    else:
        health_score = 0
    breakdown["health"] = health_score
    score += health_score

    # ── 5. No Deprecated Commands (0–10) ──────────────────────────────────────
    deprecated = [i for i in issues if i.get("type") == "deprecated_command"]
    breakdown["no_deprecated"] = 0 if deprecated else 10
    score += breakdown["no_deprecated"]

    # ── 6. No Hardcoded Values (0–10) ─────────────────────────────────────────
    hardcoded = [i for i in issues if i.get("type") == "hardcoded_value"]
    breakdown["no_hardcoded"] = 0 if hardcoded else 10
    score += breakdown["no_hardcoded"]

    # ── 7. SPL Best Practices (0–10) ──────────────────────────────────────────
    spl_score = 10
    if "index=*" in spl:
        spl_score -= 6     # full-index scan — very expensive
    if "| head " not in spl and len(spl) > 300:
        spl_score -= 2     # very long search with no result limit
    if "earliest=" not in spl and "dispatch.earliest_time" not in str(obj):
        spl_score -= 2     # no time bounds — may scan all history
    breakdown["spl_quality"] = max(0, spl_score)
    score += breakdown["spl_quality"]

    return {"score": min(score, 100), "breakdown": breakdown}


def score_app(enriched_app_data: dict[str, Any]) -> dict[str, Any]:
    all_objects = enriched_app_data.get("saved_searches", []) + enriched_app_data.get("macros", [])

    if not all_objects:
        return {
            "overall_score": 0,
            "before_score": 0,
            "grade": "F — Invisible to AI Agents",
            "grade_color": "#7f1d1d",
            "before_grade": "F — Invisible to AI Agents",
            "before_grade_color": "#7f1d1d",
            "objects_scored": 0,
            "mcp_blockers": 0,
            "pre_patch_missing": 0,
            "avg_score": 0,
            "min_score": 0,
            "max_score": 0,
        }

    object_scores: list[int] = []
    for obj in all_objects:
        scored = score_knowledge_object(obj)
        obj["score"] = scored["score"]
        obj["score_breakdown"] = scored["breakdown"]
        object_scores.append(scored["score"])

    avg = round(sum(object_scores) / len(object_scores))

    # ── After score (with AI descriptions) ────────────────────────────────────
    mcp_blockers = sum(1 for obj in all_objects if obj.get("is_mcp_blocker", False))
    pre_patch_missing = sum(1 for obj in all_objects if not obj.get("had_original_description", True))
    blocker_ratio = mcp_blockers / len(all_objects)
    penalty = round(blocker_ratio * 15)
    overall = max(0, min(100, avg - penalty))

    # ── Before score (as if tool never ran — original Splunk descriptions only) ─
    before_scores: list[int] = []
    for obj in all_objects:
        saved_mcp = obj.get("mcp_description", "")
        obj["mcp_description"] = ""           # hide AI output temporarily
        bs = score_knowledge_object(obj)
        before_scores.append(bs["score"])
        obj["mcp_description"] = saved_mcp    # restore
        # Restore correct post-AI blocker flag
        obj["is_mcp_blocker"] = (
            not obj.get("had_original_description", True)
            and not bool(saved_mcp.strip())
        )

    before_avg = round(sum(before_scores) / len(before_scores))
    before_penalty = round((pre_patch_missing / len(all_objects)) * 15)
    before_overall = max(0, min(100, before_avg - before_penalty))

    grade, grade_color = _grade(overall)
    before_grade, before_grade_color = _grade(before_overall)
    return {
        "overall_score": overall,
        "before_score": before_overall,
        "grade": grade,
        "grade_color": grade_color,
        "before_grade": before_grade,
        "before_grade_color": before_grade_color,
        "objects_scored": len(all_objects),
        "mcp_blockers": mcp_blockers,
        "pre_patch_missing": pre_patch_missing,
        "avg_score": avg,
        "min_score": min(object_scores),
        "max_score": max(object_scores),
    }


def _grade(score: int) -> tuple[str, str]:
    if score >= 80:
        return "A — Agent Ready", "#22c55e"
    if score >= 65:
        return "B — Mostly Ready", "#84cc16"
    if score >= 45:
        return "C — Needs Work", "#f59e0b"
    if score >= 25:
        return "D — Largely Broken for Agents", "#ef4444"
    return "F — Invisible to AI Agents", "#7f1d1d"
