from __future__ import annotations


def generate_conf_patch(saved_searches: list[dict[str, object]]) -> str:
    lines = [
        "# ═══════════════════════════════════════════════════════════════",
        "# MCP Semantic Description Patch",
        "# Generated by Splunk Agent-Readiness Engine",
        "#",
        "# HOW TO APPLY:",
        "#   1. Merge these stanzas into your app's default/savedsearches.conf",
        "#   2. Restart Splunk or run: splunk restart",
        "#   3. AI agents using the Splunk MCP Server will now correctly",
        "#      identify and use each search based on semantic context.",
        "# ═══════════════════════════════════════════════════════════════",
        "",
    ]

    for saved_search in saved_searches:
        name = str(saved_search.get("name", "")).strip()
        # Skip the global [default] stanza — it's not a real saved search
        if not name or name.lower() == "default":
            continue
        description = str(saved_search.get("mcp_description") or saved_search.get("description") or "").strip()
        if not description:
            continue
        lines.append(f"[{name}]")
        lines.append(f"description = {_single_line(description)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _single_line(value: str) -> str:
    return " ".join(value.replace("\r", " ").replace("\n", " ").split())

